version: '3'

services:
 
  api:
    build: ./api
    container_name: formplus-api
    command: flask --app main run -h 0.0.0.0 -p 5500
    volumes:
      - ./api:/api
    ports:
      - 5500:5500
    env_file: ".env"
    depends_on:
      - db

  db:
    image: mongo:jammy
    container_name: formplus-db
    environment:
      MONGO_INITDB_DATABASE: formplus
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
    mongodb_data:
  

